USE [master]
GO

/****** Object:  Database [DBBenhVienYHocCoTruyen]    Script Date: 6/28/2015 2:54:17 AM ******/
CREATE DATABASE [DBBenhVienYHocCoTruyen]
-- CONTAINMENT = NONE
-- ON  PRIMARY 
--( NAME = N'DBBenhVienYHocCoTruyen', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.HOANGHUYEN\MSSQL\DATA\DBBenhVienYHocCoTruyen.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
-- LOG ON 
--( NAME = N'DBBenhVienYHocCoTruyen_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.HOANGHUYEN\MSSQL\DATA\DBBenhVienYHocCoTruyen_log.ldf' , SIZE = 3456KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DBBenhVienYHocCoTruyen] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBBenhVienYHocCoTruyen].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DBBenhVienYHocCoTruyen] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DBBenhVienYHocCoTruyen] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DBBenhVienYHocCoTruyen] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DBBenhVienYHocCoTruyen] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DBBenhVienYHocCoTruyen] SET ARITHABORT OFF 
GO

ALTER DATABASE [DBBenhVienYHocCoTruyen] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DBBenhVienYHocCoTruyen] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [DBBenhVienYHocCoTruyen] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DBBenhVienYHocCoTruyen] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DBBenhVienYHocCoTruyen] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DBBenhVienYHocCoTruyen] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DBBenhVienYHocCoTruyen] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DBBenhVienYHocCoTruyen] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DBBenhVienYHocCoTruyen] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DBBenhVienYHocCoTruyen] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DBBenhVienYHocCoTruyen] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DBBenhVienYHocCoTruyen] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DBBenhVienYHocCoTruyen] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DBBenhVienYHocCoTruyen] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DBBenhVienYHocCoTruyen] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DBBenhVienYHocCoTruyen] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DBBenhVienYHocCoTruyen] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DBBenhVienYHocCoTruyen] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DBBenhVienYHocCoTruyen] SET RECOVERY FULL 
GO

ALTER DATABASE [DBBenhVienYHocCoTruyen] SET  MULTI_USER 
GO

ALTER DATABASE [DBBenhVienYHocCoTruyen] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DBBenhVienYHocCoTruyen] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DBBenhVienYHocCoTruyen] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DBBenhVienYHocCoTruyen] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DBBenhVienYHocCoTruyen] SET  READ_WRITE 
GO


